name: "release"

on:
  push
  #release:
#  types: [ created ]

env:
  GODOT_VERSION: 3.4
  EXPORT_NAME: PlanetaryDefense

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Get tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        shell: bash
      - name: Install build-essentials and mingw
        run: |
          apt-get update -y
          apt-get -y install build-essential
          apt-get -y install g++-mingw-w64-x86-64 gcc-mingw-w64-x86-64
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-pc-windows-gnu
          profile: minimal
          toolchain: stable
          override: true
      - name: Rust Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --lib --target x86_64-pc-windows-gnu
      - name: Move Build Output
        run: |
          mkdir -p target/release
          cp target/x86_64-pc-windows-gnu/release/planetary_defense.dll target/release/
      - name: Setup Godot
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Godot Windows Build
        run: |
          mkdir -v -p build/$EXPORT_NAME-windows
          godot -v --export "Windows Desktop" build/$EXPORT_NAME-windows/$EXPORT_NAME.exe
